apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "magento.fullname" . }}-config
  labels:
    {{- include "magento.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  MAGE_MODE: {{ .Values.config.mageMode | quote }}
  APP_URL: {{ .Values.config.appUrl | quote }}
  MAGENTO_BACKEND_FRONTNAME: {{ .Values.config.backendFrontname | quote }}
  MAGENTO_TIMEZONE: {{ .Values.config.timezone | quote }}
  MAGENTO_CURRENCY: {{ .Values.config.currency | quote }}
  MAGENTO_LANGUAGE: {{ .Values.config.language | quote }}
  
  MYSQL_HOST: {{ .Values.config.mysql.host | quote }}
  MYSQL_PORT: {{ .Values.config.mysql.port | quote }}
  MYSQL_DATABASE: {{ .Values.config.mysql.database | quote }}
  
  REDIS_HOST: {{ .Values.config.redis.host | quote }}
  REDIS_PORT: {{ .Values.config.redis.port | quote }}
  
  OPENSEARCH_HOST: {{ .Values.config.opensearch.host | quote }}
  OPENSEARCH_PORT: {{ .Values.config.opensearch.port | quote }}
  OPENSEARCH_INDEX_PREFIX: {{ .Values.config.opensearch.indexPrefix | quote }}
  OPENSEARCH_ENABLE_SSL: {{ .Values.config.opensearch.ssl | quote }}
  
  RABBITMQ_HOST: {{ .Values.config.rabbitmq.host | quote }}
  RABBITMQ_PORT: {{ .Values.config.rabbitmq.port | quote }}
  RABBITMQ_SSL: {{ .Values.config.rabbitmq.ssl | quote }}
  RABBITMQ_VHOST: {{ .Values.config.rabbitmq.vhost | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "magento.fullname" . }}-nginx-config
  labels:
    {{- include "magento.labels" . | nindent 4 }}
data:
  default.conf: |
    upstream fastcgi_backend {
        server 127.0.0.1:9000;
        keepalive 32;
    }
    server {
        listen 80 default_server;
        server_name _;
        set $MAGE_ROOT /var/www/html;
        set $MAGE_MODE {{ .Values.config.mageMode }};
        root $MAGE_ROOT/pub;
        index index.php;
        autoindex off;
        charset UTF-8;

        location = /health_check.php {
            try_files $uri =404;
            fastcgi_pass fastcgi_backend;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        location /static/ {
            location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|woff|woff2)$ {
                add_header Cache-Control "public";
                expires +1y;
            }
            try_files $uri $uri/ /static.php?resource=$1;
        }

        location /media/ {
            try_files $uri $uri/ /get.php$is_args$args;
        }

        location ~ (index|get|static|report|404|503)\.php$ {
            try_files $uri =404;
            fastcgi_pass fastcgi_backend;
            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
            fastcgi_read_timeout 600s;
            fastcgi_connect_timeout 600s;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        location ~* ^/(app|bin|var|generated|vendor)/ {
            deny all;
        }
    }
