apiVersion: v1
kind: Secret
metadata:
  name: {{ include "magento.fullname" . }}-secrets
  labels:
    {{- include "magento.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.secrets.mysqlUser | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  RABBITMQ_USER: {{ .Values.secrets.rabbitmqUser | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitmqPassword | quote }}
  MAGENTO_ADMIN_USERNAME: {{ .Values.secrets.adminUser | quote }}
  MAGENTO_ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  MAGENTO_CRYPT_KEY: {{ .Values.secrets.cryptKey | quote }}
