apiVersion: v1
kind: Service
metadata:
  name: {{ include "magento.fullname" . }}-service
  labels:
    {{- include "magento.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "magento.selectorLabels" . | nindent 4 }}
