apiVersion: v1
kind: ConfigMap
metadata:
  name: magento-config
  namespace: magento
  labels:
    app.kubernetes.io/name: magento2
    app.kubernetes.io/component: configuration
data:
  APP_ENV: "production"
  MAGE_MODE: "production"
  MAGE_PROFILER: ""
  
  # External Managed Services Endpoints (AWS RDS, ElastiCache, OpenSearch, Amazon MQ)
  MYSQL_HOST: "magento-rds-prod.cr4xample.us-east-1.rds.amazonaws.com"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "magento2_prod"
  
  REDIS_HOST: "magento-redis-rep-group.xample.ng.0001.use1.cache.amazonaws.com"
  REDIS_PORT: "6379"
  
  OPENSEARCH_HOST: "search-magento-opensearch-xample.us-east-1.es.amazonaws.com"
  OPENSEARCH_PORT: "443"
  OPENSEARCH_INDEX_PREFIX: "magento2_prod"
  OPENSEARCH_ENABLE_SSL: "true"
  
  RABBITMQ_HOST: "b-xample-id.mq.us-east-1.amazonaws.com"
  RABBITMQ_PORT: "5671"
  RABBITMQ_SSL: "true"
  RABBITMQ_VHOST: "/"
  
  # Base Store URL
  APP_URL: "https://shop.enterprise-magento.com"
  MAGENTO_BACKEND_FRONTNAME: "admin_enterprise"
  MAGENTO_LANGUAGE: "en_US"
  MAGENTO_CURRENCY: "USD"
  MAGENTO_TIMEZONE: "UTC"
