apiVersion: v1
kind: ServiceAccount
metadata:
  name: magento-sa
  namespace: magento
  labels:
    app.kubernetes.io/name: magento2
  annotations:
    # IRSA: Allows Pod to assume AWS IAM Role to read AWS Secrets Manager and S3 media
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/magento-pod-irsa-role
