apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-media-pvc
  namespace: magento
  labels:
    app.kubernetes.io/name: magento2
    app.kubernetes.io/component: media-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 100Gi
